name: generate pacman game

on:
  schedule: # Ejecuta automáticamente cada 24 horas a medianoche
    - cron: "0 0 * * *"
  workflow_dispatch: # Permite ejecutar el job manualmente en cualquier momento desde la pestaña Actions
  push: # Ejecuta en cada push a la rama main
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write  # Permiso para escribir en el repositorio
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Límite de tiempo para evitar ejecuciones prolongadas

    steps:
      - name: Generar pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}  # Usa el propietario del repositorio como usuario

      # Sube el contenido generado a una rama dedicada
      # El contenido estará disponible en https://raw.githubusercontent.com/<usuario>/<usuario>/output/pacman-contribution-graph.svg o como página de GitHub
      - name: Subir pacman-contribution-graph.svg a la rama output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output  # Rama donde se subirá el archivo generado
          build_dir: dist  # Directorio donde se genera el archivo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token necesario para la autenticación